### Day Objectives
### Date : 31-10-2019
* Numpy

In [2]:
import numpy as np

In [3]:
k = np.array([1,2,3,4])
type(k)

numpy.ndarray

In [6]:
list1 = [1,2,3,4]
list2 = [2,3,4,5]
list3 = list(map(lambda x,y:x*y,list1,list2))
list3


[2, 6, 12, 20]

In [9]:
l1 = np.array([1,2,3,4])
l2 = np.array([2,3,4,5])
print(l1*l2)
print(l1+l2)

[ 2  6 12 20]
[3 5 7 9]


In [10]:
list1

[1, 2, 3, 4]

In [11]:
sqlist = [i**2 for i in list1]
sqlist

[1, 4, 9, 16]

In [12]:
sq = list(map(lambda i: i**2,list1))
sq

[1, 4, 9, 16]

In [13]:
narray = np.array([30,40,50,60])
narray**2

array([ 900, 1600, 2500, 3600], dtype=int32)

In [22]:
a = np.arange(1,10,2.5)
a


array([1. , 3.5, 6. , 8.5])

In [28]:
l = np.array([[2,3,4,5],[1,2,3,4]])
type(l)
l

array([[2, 3, 4, 5],
       [1, 2, 3, 4]])

In [29]:
l[1]

array([1, 2, 3, 4])

In [31]:
l[0]

array([2, 3, 4, 5])

In [32]:
l[:1]

array([[2, 3, 4, 5]])

In [33]:
l[1:]

array([[1, 2, 3, 4]])

In [39]:
l[1:5]

array([[1, 2, 3, 4]])

In [40]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
a.ndim

2

In [43]:
a.shape

(3, 5)

In [44]:
a.dtype

dtype('int32')

In [45]:
a.itemsize

4

In [46]:
a.size

15

In [49]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [52]:
np.ones((3,4),dtype = 'int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [59]:
np.eye(3,3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [56]:
np.tile([5,4],(3,4))

array([[5, 4, 5, 4, 5, 4, 5, 4],
       [5, 4, 5, 4, 5, 4, 5, 4],
       [5, 4, 5, 4, 5, 4, 5, 4]])

In [57]:
np.full([5,6],8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [60]:
np.random.random([5,4])

array([[0.86268557, 0.57934413, 0.62135538, 0.05794873],
       [0.11855783, 0.66325504, 0.66091626, 0.5735383 ],
       [0.73908699, 0.28857147, 0.81517888, 0.01721012],
       [0.67886659, 0.79558195, 0.34610007, 0.6380414 ],
       [0.8933528 , 0.15546094, 0.3838422 , 0.76414915]])

In [61]:
np.random.randint(10,20,[5,4])

array([[13, 15, 14, 14],
       [17, 14, 11, 14],
       [12, 10, 16, 11],
       [15, 18, 11, 18],
       [10, 17, 18, 14]])

In [77]:
m = np.arange(24).reshape(4,3,2,1)
m

array([[[[ 0],
         [ 1]],

        [[ 2],
         [ 3]],

        [[ 4],
         [ 5]]],


       [[[ 6],
         [ 7]],

        [[ 8],
         [ 9]],

        [[10],
         [11]]],


       [[[12],
         [13]],

        [[14],
         [15]],

        [[16],
         [17]]],


       [[[18],
         [19]],

        [[20],
         [21]],

        [[22],
         [23]]]])

In [78]:
a = [3,4,5]
a = np.array(a)
print(np.sqrt(a))
print(np.square(a))
print(np.tan(a))
print(np.exp(a))
print(np.log(a))

[1.73205081 2.         2.23606798]
[ 9 16 25]
[-0.14254654  1.15782128 -3.38051501]
[ 20.08553692  54.59815003 148.4131591 ]
[1.09861229 1.38629436 1.60943791]


In [80]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [86]:
k = np.random.randint(1,60,size=(3,3,3))
k.sum()
k.min()
k.max()


59

In [88]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
b.sum(axis = 1)

array([ 6, 22, 38])

In [91]:
b.cumsum(axis=1) 

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [92]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [100]:
a = np.floor(10*np.random.random((3,4)))
a

array([[1., 0., 7., 6.],
       [2., 2., 9., 8.],
       [0., 2., 6., 7.]])

In [104]:
a=a.ravel()
a

array([1., 0., 7., 6., 2., 2., 9., 8., 0., 2., 6., 7.])

In [105]:
a[2]

7.0

In [107]:
n = np.random.randint(20,40,(3,3))
n

array([[38, 28, 27],
       [33, 35, 20],
       [38, 39, 28]])

In [108]:
n.T

array([[38, 33, 38],
       [28, 35, 39],
       [27, 20, 28]])

In [109]:
n

array([[38, 28, 27],
       [33, 35, 20],
       [38, 39, 28]])

In [7]:
n = np.random.randint(20,40,(3,4))
n

array([[39, 31, 34, 35],
       [38, 30, 37, 31],
       [26, 21, 34, 36]])

In [11]:
n.reshape(-1,2)

array([[39, 31],
       [34, 35],
       [38, 30],
       [37, 31],
       [26, 21],
       [34, 36]])

In [5]:
n

array([[33, 29],
       [34, 25],
       [39, 39],
       [34, 35],
       [23, 30],
       [29, 37]])

In [12]:
n = np.random.randint(20,40,(3,4))
n

array([[31, 25, 38, 25],
       [28, 24, 27, 35],
       [22, 30, 35, 37]])

In [16]:
np.hsplit(n,2)

[array([[31, 25],
        [28, 24],
        [22, 30]]), array([[38, 25],
        [27, 35],
        [35, 37]])]

In [17]:
np.vsplit(n,3)

[array([[31, 25, 38, 25]]),
 array([[28, 24, 27, 35]]),
 array([[22, 30, 35, 37]])]

In [18]:
n

array([[31, 25, 38, 25],
       [28, 24, 27, 35],
       [22, 30, 35, 37]])

In [30]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
b = a
b

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
a is b

True

In [33]:
c = a.view()
c

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
b.shape = 3,2
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
a.shape

(3, 2)

In [38]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
c = a.view()
c

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
c.shape = 3,2
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [42]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
m = np.arange(6).reshape(2,3)
m

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
k = m.copy()
k

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
k is m

False

In [50]:
a = np.arange(12)**2 
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [51]:
i = np.array( [ 1,1,3,8,5 ] )
i

array([1, 1, 3, 8, 5])

In [52]:
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [53]:
import numpy as np

In [54]:
k = np.array([1,2,3,4])
k

array([1, 2, 3, 4])

In [58]:
l1 = [1,2,3,4]
l2 = [2,3,4,5]
for i in range(len(l1)):
    print(l1[i]*l2[i])

l3 = list(map(lambda x,y:x*y,l1,l2))
l3

[2, 6, 12, 20]

In [59]:
nl1 = np.array(l1)
nl2 = np.array(l2)
nl1*nl2

array([ 2,  6, 12, 20])

In [60]:
nl1+nl2

array([3, 5, 7, 9])

In [61]:
l1

[1, 2, 3, 4]

In [63]:
sql = [i**2 for i in l1]
sql

[1, 4, 9, 16]

In [64]:
nl1**2

array([ 1,  4,  9, 16], dtype=int32)

In [73]:
l = [i for i in range(1,10,2)]
l

[1, 3, 5, 7, 9]

In [75]:
l = np.arange(1,10,2.5)
l

array([1. , 3.5, 6. , 8.5])

In [76]:
a = np.array([[1,2,3,4],[3,4,5,6]])
a

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [77]:
a.ndim

2

In [78]:
a.shape

(2, 4)

In [79]:
a.size

8

In [81]:
a.dtype

dtype('int32')

In [82]:
a.itemsize

4

In [83]:
a.data

In [87]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [88]:
a.dtype

dtype('int32')

In [89]:
a.itemsize

4

In [90]:
a.ndim

2

In [93]:
m = np.zeros((2,3),dtype = 'int')

array([[0, 0, 0],
       [0, 0, 0]])

In [96]:
np.ones((4,6),dtype='int')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [97]:
np.empty( (2,3) ) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [99]:
np.linspace(1,20,9)

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [100]:
c = np.arange(24).reshape(2,3,4)  
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [101]:
c.dtype

dtype('int32')

In [105]:
a = np.array([1,2,3,4])
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [106]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [108]:
a<1.5

array([ True, False, False, False])

In [110]:
A=np.arange(4).reshape(2,2)
B=np.arange(4).reshape(2,2)
print(A)
print(B)
A.dot(B)


[[0 1]
 [2 3]]
[[0 1]
 [2 3]]


array([[ 2,  3],
       [ 6, 11]])

In [111]:
A@B

array([[ 2,  3],
       [ 6, 11]])

In [112]:
a = np.random.random((2,3))
a

array([[0.35647335, 0.30885272, 0.26120462],
       [0.42474668, 0.42703455, 0.62097631]])

In [115]:
a = np.random.randint(1,10,(2,3))
a

array([[2, 1, 4],
       [7, 9, 7]])

In [117]:
a.sum()

30

In [118]:
a.max()

9

In [119]:
a.min()

1

In [120]:
a.sum(axis = 0)

array([ 9, 10, 11])

In [121]:
np.cumsum(a)

array([ 2,  3,  7, 14, 23, 30], dtype=int32)

In [122]:
a

array([[2, 1, 4],
       [7, 9, 7]])

In [123]:
np.exp(a)

array([[7.38905610e+00, 2.71828183e+00, 5.45981500e+01],
       [1.09663316e+03, 8.10308393e+03, 1.09663316e+03]])

In [124]:
np.log(a)

array([[0.69314718, 0.        , 1.38629436],
       [1.94591015, 2.19722458, 1.94591015]])

In [125]:
np.square(a)

array([[ 4,  1, 16],
       [49, 81, 49]], dtype=int32)

In [126]:
a[1:]

array([[7, 9, 7]])

In [128]:
a[::-1]

array([[7, 9, 7],
       [2, 1, 4]])

In [130]:
a[1:2:2]

array([[7, 9, 7]])

In [132]:
def f(x,y):
     return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [135]:
b[0:3,2]

array([ 2, 12, 22])

In [140]:
b=b.ravel()
b

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [142]:
b[-1]

43

In [143]:
a

array([[2, 1, 4],
       [7, 9, 7]])

In [144]:
a.T

array([[2, 7],
       [1, 9],
       [4, 7]])

In [145]:
a

array([[2, 1, 4],
       [7, 9, 7]])

In [147]:
a.reshape(3,-1)

array([[2, 1],
       [4, 7],
       [9, 7]])

In [149]:
a

array([[2, 1, 4],
       [7, 9, 7]])

In [152]:
np.hsplit(a,3)

[array([[2],
        [7]]), array([[1],
        [9]]), array([[4],
        [7]])]

In [153]:
a

array([[2, 1, 4],
       [7, 9, 7]])

In [154]:
b = a
b

array([[2, 1, 4],
       [7, 9, 7]])

In [155]:
b is a

True

In [156]:
a.shape

(2, 3)

In [157]:
b.shape

(2, 3)

In [165]:
a= np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [166]:
b = a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [170]:
a.shape

(20,)

In [173]:
k = np.random.randint(10,20,(2,3))
k

array([[11, 16, 11],
       [17, 18, 10]])

In [175]:
m = k
m

array([[11, 16, 11],
       [17, 18, 10]])

In [176]:
m.shape

(2, 3)

In [181]:
k.shape

(2, 3)